local binaries = {
    encrypt = "bin/composer/composer-encrypt.exe",
    decrypt = "bin/composer/composer-decrypt.exe",
    fxc = "bin/dx9/fxc.exe"
}

if jit.os == "Linux" then
    binaries.encrypt = "wine " .. binaries.encrypt
    binaries.decrypt = "wine " .. binaries.decrypt
    binaries.fxc = "wine " .. binaries.fxc
else
    binaries.encrypt = "cmd /c " .. binaries.encrypt:gsub("/", "\\")
    binaries.decrypt = "cmd /c " .. binaries.decrypt:gsub("/", "\\")
    binaries.fxc = "cmd /c " .. binaries.fxc:gsub("/", "\\")
end

local separators = {Windows = "\\", Linux = "/"}

local vertexShaderNames = {
    "convolution",
    "debug",
    "decal",
    "detail_object_type0",
    "detail_object_type1",
    "effect",
    "effect_multitexture",
    "effect_multitexture_screenspace",
    "effect_zsprite",
    "environment_diffuse_light",
    "environment_diffuse_light_ff",
    "environment_fog",
    "environment_fog_screen",
    "environment_lightmap",
    "environment_reflection_bumped",
    "environment_reflection_flat",
    "environment_lightmap_mask",
    "environment_reflection_mirror",
    "environment_reflection_radiosity",
    "environment_shadow",
    "environment_specular_light",
    "environment_specular_spot_light",
    "environment_specular_lightmap",
    "environment_texture",
    "lens_flare",
    "model_fogged",
    "model",
    "model_ff",
    "model_fast", -- seems to be related to ui widget rendering
    "model_scenery",
    "model_active_camouflage",
    "model_active_camouflage_ff",
    "model_fog_screen",
    "model_shadow",
    "model_zbuffer",
    "screen",
    "screen2",
    "transparent_generic",
    "transparent_generic_lit_m",
    "transparent_generic_m",
    "transparent_generic_object_centered",
    "transparent_generic_object_centered_m",
    "transparent_generic_reflection",
    "transparent_generic_reflection_m",
    "transparent_generic_screenspace",
    "transparent_generic_screenspace_m",
    "transparent_generic_viewer_centered",
    "transparent_generic_viewer_centered_m",
    "transparent_glass_diffuse_light",
    "transparent_glass_diffuse_light_m",
    "transparent_glass_reflection_bumped",
    "transparent_glass_reflection_bumped_m",
    "transparent_glass_reflection_flat",
    "transparent_glass_reflection_flat_m",
    "transparent_glass_reflection_mirror",
    "transparent_glass_tint",
    "transparent_glass_tint_m",
    "transparent_meter",
    "transparent_meter_m",
    "transparent_plasma_m",
    "transparent_water_opacity",
    "transparent_water_opacity_m",
    "transparent_water_reflection",
    "transparent_water_reflection_m"
}

--[[
_rasterizer_vertex_shader,
_rasterizer_vs_transparent_water_reflection_m,
_rasterizer_vs_transparent_water_reflection,
_rasterizer_vs_transparent_water_opacity_m,
_rasterizer_vs_transparent_water_opacity,
_rasterizer_vs_transparent_plasma_m,
_rasterizer_vs_transparent_meter_m,
_rasterizer_vs_transparent_meter,
_rasterizer_vs_transparent_glass_tint_m,
_rasterizer_vs_transparent_glass_tint,
_rasterizer_vs_transparent_glass_reflection_mirror,
_rasterizer_vs_transparent_glass_reflection_flat_m,
_rasterizer_vs_transparent_glass_reflection_flat,
_rasterizer_vs_transparent_glass_reflection_bumped_m,
_rasterizer_vs_transparent_glass_reflection_bumped,
_rasterizer_vs_transparent_glass_diffuse_light_m,
_rasterizer_vs_transparent_glass_diffuse_light,
_rasterizer_vs_transparent_generic_viewer_centered_m,
_rasterizer_vs_transparent_generic_viewer_centered,
_rasterizer_vs_transparent_generic_screenspace_m,
_rasterizer_vs_transparent_generic_screenspace,
_rasterizer_vs_transparent_generic_reflection_m,
_rasterizer_vs_transparent_generic_reflection,
_rasterizer_vs_transparent_generic_object_centered_m,
_rasterizer_vs_transparent_generic_object_centered,
_rasterizer_vs_transparent_generic_m,
_rasterizer_vs_transparent_generic_lit_m,
_rasterizer_vs_transparent_generic,
_rasterizer_vs_screen2,
_rasterizer_vs_screen,
_rasterizer_vs_model_zbuffer,
_rasterizer_vs_model_shadow,
_rasterizer_vs_model_fog_screen,
_rasterizer_vs_model_active_camouflage_ff,
_rasterizer_vs_model_active_camouflage,
_rasterizer_vs_model_scenery,
_rasterizer_vs_model_fast,
_rasterizer_vs_model_ff,
_rasterizer_vs_model,
_rasterizer_vs_model_fogged,
_rasterizer_vs_lens_flare,
_rasterizer_vs_environment_texture,
_rasterizer_vs_environment_specular_lightmap,
_rasterizer_vs_environment_specular_spot_light,
_rasterizer_vs_environment_specular_light,
_rasterizer_vs_environment_shadow,
_rasterizer_vs_environment_reflection_radiosity,
_rasterizer_vs_environment_reflection_mirror,
_rasterizer_vs_environment_reflection_lightmap_mask,
_rasterizer_vs_environment_reflection_flat,
_rasterizer_vs_environment_reflection_bumped,
_rasterizer_vs_environment_lightmap,
_rasterizer_vs_environment_fog_screen,
_rasterizer_vs_environment_fog,
_rasterizer_vs_environment_diffuse_light_ff,
_rasterizer_vs_environment_diffuse_light,
_rasterizer_vs_effect_zsprite,
_rasterizer_vs_effect_multitexture_screenspace,
_rasterizer_vs_effect_multitexture,
_rasterizer_vs_effect,
_rasterizer_vs_detail_object_type1,
_rasterizer_vs_detail_object_type0,
_rasterizer_vs_decal,
_rasterizer_vs_debug,
_rasterizer_vs_convolution,
]]

local pixelShaderNames = {
    "widget_sprite",
    "active_camouflage_draw",
    "effect_multitexture_nonlinear_tint",
    "effect_multitexture_nonlinear_tint_add",
    "effect_multitexture_nonlinear_tint_alpha_blend",
    "effect_multitexture_nonlinear_tint_double_multiply",
    "effect_multitexture_nonlinear_tint_multiply",
    "effect_multitexture_nonlinear_tint_multiply_add",
    "effect_multitexture_normal_tint",
    "effect_multitexture_normal_tint_add",
    "effect_multitexture_normal_tint_alpha_blend",
    "effect_multitexture_normal_tint_double_multiply",
    "effect_multitexture_normal_tint_multiply",
    "effect_multitexture_normal_tint_multiply_add",
    "effect_nonlinear_tint",
    "effect_nonlinear_tint_add",
    "effect_nonlinear_tint_alpha_blend",
    "effect_nonlinear_tint_double_multiply",
    "effect_nonlinear_tint_multiply",
    "effect_nonlinear_tint_multiply_add",
    "effect_normal_tint",
    "effect_normal_tint_add",
    "effect_normal_tint_alpha_blend",
    "effect_normal_tint_double_multiply",
    "effect_normal_tint_multiply",
    "effect_normal_tint_multiply_add",
    "environment_diffuse_lights",
    "environment_fog",
    "environment_lightmap_no_illumination",
    "environment_lightmap_no_illumination_no_lightmap",
    "environment_lightmap_no_lightmap",
    "environment_lightmap_normal",
    "environment_reflection_bumped",
    "environment_reflection_flat",
    "environment_reflection_flat_specular",
    "environment_reflection_lightmap_mask",
    "environment_reflection_mirror_bumped",
    "environment_reflection_mirror_flat",
    "environment_reflection_mirror_flat_specular",
    "environment_reflection_radiosity",
    "environment_shadow",
    "environment_specular_light_bumped",
    "environment_specular_light_flat",
    "environment_specular_lightmap_bumped",
    "environment_specular_lightmap_flat",
    "environment_texture_blended_biased_add_biased_add",
    "environment_texture_blended_biased_add_biased_multiply",
    "environment_texture_blended_biased_add_multiply",
    "environment_texture_blended_biased_multiply_biased_add",
    "environment_texture_blended_biased_multiply_biased_multiply",
    "environment_texture_blended_biased_multiply_multiply",
    "environment_texture_blended_multiply_biased_add",
    "environment_texture_blended_multiply_biased_multiply",
    "environment_texture_blended_multiply_multiply",
    "environment_texture_normal_biased_add_biased_add",
    "environment_texture_normal_biased_add_biased_multiply",
    "environment_texture_normal_biased_add_multiply",
    "environment_texture_normal_biased_multiply_biased_add",
    "environment_texture_normal_biased_multiply_biased_multiply",
    "environment_texture_normal_biased_multiply_multiply",
    "environment_texture_normal_multiply_biased_add",
    "environment_texture_normal_multiply_biased_multiply",
    "environment_texture_normal_multiply_multiply",
    "environment_texture_specular_mask_biased_add_biased_add",
    "environment_texture_specular_mask_biased_add_biased_multiply",
    "environment_texture_specular_mask_biased_add_multiply",
    "environment_texture_specular_mask_biased_multiply_biased_add",
    "environment_texture_specular_mask_biased_multiply_biased_multiply",
    "environment_texture_specular_mask_biased_multiply_multiply",
    "environment_texture_specular_mask_multiply_biased_add",
    "environment_texture_specular_mask_multiply_biased_multiply",
    "environment_texture_specular_mask_multiply_multiply",
    "model_environment",
    "model_mask_change_color",
    "model_mask_multipurpose",
    "model_mask_none",
    "model_mask_reflection",
    "model_mask_self_illumination",
    "screen_effect",
    "screen_effect_non_video",
    "screen_effect_non_video_convolution_mask",
    "screen_effect_non_video_convolution_none",
    "screen_effect_non_video_no_convolution_mask",
    "screen_effect_video",
    "screen_flash",
    "screen_meter",
    "screen_multitexture_add_add",
    "screen_multitexture_add_dot",
    "screen_multitexture_add_multiply2x",
    "screen_multitexture_add_multiply",
    "screen_multitexture_add_subtract",
    "screen_multitexture_dot_add",
    "screen_multitexture_dot_dot",
    "screen_multitexture_dot_multiply2x",
    "screen_multitexture_dot_multiply",
    "screen_multitexture_dot_subtract",
    "screen_multitexture_multiply2x_add",
    "screen_multitexture_multiply2x_dot",
    "screen_multitexture_multiply2x_multiply2x",
    "screen_multitexture_multiply2x_multiply",
    "screen_multitexture_multiply2x_subtract",
    "screen_multitexture_multiply_add",
    "screen_multitexture_multiply_dot",
    "screen_multitexture_multiply_multiply2x",
    "screen_multitexture_multiply_multiply",
    "screen_multitexture_multiply_subtract",
    "screen_multitexture_subtract_add",
    "screen_multitexture_subtract_dot",
    "screen_multitexture_subtract_multiply2x",
    "screen_multitexture_subtract_multiply",
    "screen_multitexture_subtract_subtract",
    "screen_normal",
    "shadow_convolve",
    "sun_glow_convolve",
    "sun_glow_draw",
    "transparent_generic",
    "transparent_glass_diffuse",
    "transparent_glass_reflection_bumped",
    "transparent_glass_reflection_flat",
    "transparent_glass_reflection_mirror",
    "transparent_glass_tint",
    "transparent_meter",
    "transparent_plasma",
    "transparent_water_bumpmap_convolution",
    "transparent_water_opacity",
    "transparent_water_reflection"
}

local pixelShaderFunctions = {
    active_camouflage_draw = {NoEdgeTint = 2, TintEdgeDensity = 1},
    effect_multitexture_nonlinear_tint = {EffectMultitextureNonlinearTint = 1},
    effect_multitexture_nonlinear_tint_add = {EffectMultitextureNonlinearTintAdd = 1},
    effect_multitexture_nonlinear_tint_alpha_blend = {EffectMultitextureNonlinearTintAlphaBlend = 1},
    effect_multitexture_nonlinear_tint_double_multiply = {
        EffectMultitextureNonlinearTintDoubleMultiply = 1
    },
    effect_multitexture_nonlinear_tint_multiply = {EffectMultitextureNonlinearTintMultiply = 1},
    effect_multitexture_nonlinear_tint_multiply_add = {
        EffectMultitextureNonlinearTintMultiplyAdd = 1
    },
    effect_multitexture_normal_tint = {EffectMultitextureNormalTint = 1},
    effect_multitexture_normal_tint_add = {EffectMultitextureNormalTintAdd = 1},
    effect_multitexture_normal_tint_alpha_blend = {EffectMultitextureNormalTintAlphaBlend = 1},
    effect_multitexture_normal_tint_double_multiply = {
        EffectMultitextureNormalTintDoubleMultiply = 1
    },
    effect_multitexture_normal_tint_multiply = {EffectMultitextureNormalTintMultiply = 1},
    effect_multitexture_normal_tint_multiply_add = {EffectMultitextureNormalTintMultiplyAdd = 1},
    effect_nonlinear_tint = {EffectNonlinearTint = 1},
    effect_nonlinear_tint_add = {EffectNonlinearTintAdd = 1},
    effect_nonlinear_tint_alpha_blend = {EffectNonlinearTintAlphaBlend = 1},
    effect_nonlinear_tint_double_multiply = {EffectNonlinearTintDoubleMultiply = 1},
    effect_nonlinear_tint_multiply = {EffectNonlinearTintMultiply = 1},
    effect_nonlinear_tint_multiply_add = {EffectNonlinearTintMultiplyAdd = 1},
    effect_normal_tint = {EffectNormalTint = 1},
    effect_normal_tint_add = {EffectNormalTintAdd = 1},
    effect_normal_tint_alpha_blend = {EffectNormalTintAlphaBlend = 1},
    effect_normal_tint_double_multiply = {EffectNormalTintDoubleMultiply = 1},
    effect_normal_tint_multiply = {EffectNormalTintMultiply = 1},
    effect_normal_tint_multiply_add = {EffectNormalTintMultiplyAdd = 1},
    environment_diffuse_lights = {EnvironmentDiffuseLights = 1},
    environment_fog = {EnvironmentFog = 1},
    environment_lightmap_no_illumination = {EnvironmentLightmapNoIllumination = 1},
    environment_lightmap_no_illumination_no_lightmap = {
        EnvironmentLightmapNoIlluminationNoLightmap = 1
    },
    environment_lightmap_no_lightmap = {EnvironmentLightmapNoLightmap = 1},
    environment_lightmap_normal = {EnvironmentLightmapNormal = 1},
    environment_reflection_bumped = {EnvironmentReflectionBumped = 1},
    environment_reflection_flat = {EnvironmentReflectionFlat = 1},
    environment_reflection_flat_specular = {EnvironmentReflectionFlatSpecular = 1},
    environment_reflection_lightmap_mask = {EnvironmentReflectionLightmapMask = 1},
    environment_reflection_mirror_bumped = {EnvironmentReflectionMirrorBumped = 1},
    environment_reflection_mirror_flat = {EnvironmentReflectionMirrorFlat = 1},
    environment_reflection_mirror_flat_specular = {EnvironmentReflectionMirrorFlatSpecular = 1},
    environment_reflection_radiosity = {EnvironmentReflectionRadiosity = 1},
    environment_shadow = {EnvironmentShadow = 1},
    environment_specular_light_bumped = {
        SpecularLightBumped = 1,
        EnvironmentSpecularLightBumped = 1 -- Add full camel case name support for this shader
    },
    environment_specular_light_flat = {EnvironmentSpecularLightFlat = 1},
    environment_specular_lightmap_bumped = {EnvironmentSpecularLightmapBumped = 1},
    environment_specular_lightmap_flat = {EnvironmentSpecularLightmapFlat = 1},
    environment_texture_blended_biased_add_biased_add = {
        EnvironmentTextureBlendedBiasedAddBiasedAdd = 1
    },
    environment_texture_blended_biased_add_biased_multiply = {
        EnvironmentTextureBlendedBiasedAddBiasedMultiply = 1
    },
    environment_texture_blended_biased_add_multiply = {
        EnvironmentTextureBlendedBiasedAddMultiply = 1
    },
    environment_texture_blended_biased_multiply_biased_add = {
        EnvironmentTextureBlendedBiasedMultiplyBiasedAdd = 1
    },
    environment_texture_blended_biased_multiply_biased_multiply = {
        EnvironmentTextureBlendedBiasedMultiplyBiasedMultiply = 1
    },
    environment_texture_blended_biased_multiply_multiply = {
        EnvironmentTextureBlendedBiasedMultiplyMultiply = 1
    },
    environment_texture_blended_multiply_biased_add = {
        EnvironmentTextureBlendedMultiplyBiasedAdd = 1
    },
    environment_texture_blended_multiply_biased_multiply = {
        EnvironmentTextureBlendedMultiplyBiasedMultiply = 1
    },
    environment_texture_blended_multiply_multiply = {EnvironmentTextureBlendedMultiplyMultiply = 1},
    environment_texture_normal_biased_add_biased_add = {
        EnvironmentTextureNormalBiasedAddBiasedAdd = 1
    },
    environment_texture_normal_biased_add_biased_multiply = {
        EnvironmentTextureNormalBiasedAddBiasedMultiply = 1
    },
    environment_texture_normal_biased_add_multiply = {EnvironmentTextureNormalBiasedAddMultiply = 1},
    environment_texture_normal_biased_multiply_biased_add = {
        EnvironmentTextureNormalBiasedMultiplyBiasedAdd = 1
    },
    environment_texture_normal_biased_multiply_biased_multiply = {
        EnvironmentTextureNormalBiasedMultiplyBiasedMultiply = 1
    },
    environment_texture_normal_biased_multiply_multiply = {
        EnvironmentTextureNormalBiasedMultiplyMultiply = 1
    },
    environment_texture_normal_multiply_biased_add = {EnvironmentTextureNormalMultiplyBiasedAdd = 1},
    environment_texture_normal_multiply_biased_multiply = {
        EnvironmentTextureNormalMultiplyBiasedMultiply = 1
    },
    environment_texture_normal_multiply_multiply = {EnvironmentTextureNormalMultiplyMultiply = 1},
    environment_texture_specular_mask_biased_add_biased_add = {
        EnvironmentTextureSpecularMaskBiasedAddBiasedAdd = 1
    },
    environment_texture_specular_mask_biased_add_biased_multiply = {
        EnvironmentTextureSpecularMaskBiasedAddBiasedMultiply = 1
    },
    environment_texture_specular_mask_biased_add_multiply = {
        EnvironmentTextureSpecularMaskBiasedAddMultiply = 1
    },
    environment_texture_specular_mask_biased_multiply_biased_add = {
        EnvironmentTextureSpecularMaskBiasedMultiplyBiasedAdd = 1
    },
    environment_texture_specular_mask_biased_multiply_biased_multiply = {
        EnvironmentTextureSpecularMaskBiasedMultiplyBiasedMultiply = 1
    },
    environment_texture_specular_mask_biased_multiply_multiply = {
        EnvironmentTextureSpecularMaskBiasedMultiplyMultiply = 1
    },
    environment_texture_specular_mask_multiply_biased_add = {
        EnvironmentTextureSpecularMaskMultiplyBiasedAdd = 1
    },
    environment_texture_specular_mask_multiply_biased_multiply = {
        EnvironmentTextureSpecularMaskMultiplyBiasedMultiply = 1
    },
    environment_texture_specular_mask_multiply_multiply = {
        EnvironmentTextureSpecularMaskMultiplyMultiply = 1
    },
    model_environment = {
        EnvironmentNoMaskDetailAfterReflectionBiasedAdd = 1,
        EnvironmentNoMaskDetailAfterReflectionBiasedAddComplexFog = 2,
        EnvironmentNoMaskDetailAfterReflectionBiasedMultiply = 3,
        EnvironmentNoMaskDetailAfterReflectionBiasedMultiplyComplexFog = 4,
        EnvironmentNoMaskDetailAfterReflectionMultiply = 5,
        EnvironmentNoMaskDetailAfterReflectionMultiplyComplexFog = 6,
        EnvironmentNoMaskDetailBeforeReflectionBiasedAdd = 7,
        EnvironmentNoMaskDetailBeforeReflectionBiasedAddComplexFog = 8,
        EnvironmentNoMaskDetailBeforeReflectionBiasedMultiply = 9,
        EnvironmentNoMaskDetailBeforeReflectionBiasedMultiplyComplexFog = 10,
        EnvironmentNoMaskDetailBeforeReflectionMultiply = 11,
        EnvironmentNoMaskDetailBeforeReflectionMultiplyComplexFog = 12
    },
    model_mask_change_color = {
        ChangeColorMaskDetailAfterReflectionBiasedAdd = 5,
        ChangeColorMaskDetailAfterReflectionBiasedAddComplexFog = 6,
        ChangeColorMaskDetailAfterReflectionBiasedMultiply = 7,
        ChangeColorMaskDetailAfterReflectionBiasedMultiplyComplexFog = 8,
        ChangeColorMaskDetailAfterReflectionMultiply = 9,
        ChangeColorMaskDetailAfterReflectionMultiplyComplexFog = 10,
        ChangeColorMaskDetailBeforeReflectionBiasedAdd = 11,
        ChangeColorMaskDetailBeforeReflectionBiasedAddComplexFog = 12,
        ChangeColorMaskDetailBeforeReflectionBiasedMultiply = 13,
        ChangeColorMaskDetailBeforeReflectionBiasedMultiplyComplexFog = 14,
        ChangeColorMaskDetailBeforeReflectionMultiply = 15,
        ChangeColorMaskDetailBeforeReflectionMultiplyComplexFog = 16,
        ChangeColorMaskInverseDetailAfterReflectionBiasedAdd = 17,
        ChangeColorMaskInverseDetailAfterReflectionBiasedAddComplexFog = 18,
        ChangeColorMaskInverseDetailAfterReflectionBiasedMultiply = 19,
        ChangeColorMaskInverseDetailAfterReflectionBiasedMultiplyComplexFog = 20,
        ChangeColorMaskInverseDetailAfterReflectionMultiply = 21,
        ChangeColorMaskInverseDetailAfterReflectionMultiplyComplexFog = 22,
        ChangeColorMaskInverseDetailBeforeReflectionBiasedAdd = 23,
        ChangeColorMaskInverseDetailBeforeReflectionBiasedAddComplexFog = 24,
        ChangeColorMaskInverseDetailBeforeReflectionBiasedMultiply = 1,
        ChangeColorMaskInverseDetailBeforeReflectionBiasedMultiplyComplexFog = 2,
        ChangeColorMaskInverseDetailBeforeReflectionMultiply = 3,
        ChangeColorMaskInverseDetailBeforeReflectionMultiplyComplexFog = 4
    },
    model_mask_multipurpose = {
        MultipurposeMaskDetailAfterReflectionBiasedAdd = 2,
        MultipurposeMaskDetailAfterReflectionBiasedAddComplexFog = 3,
        MultipurposeMaskDetailAfterReflectionBiasedMultiply = 4,
        MultipurposeMaskDetailAfterReflectionBiasedMultiplyComplexFog = 5,
        MultipurposeMaskDetailAfterReflectionMultiply = 6,
        MultipurposeMaskDetailAfterReflectionMultiplyComplexFog = 7,
        MultipurposeMaskDetailBeforeReflectionBiasedAdd = 8,
        MultipurposeMaskDetailBeforeReflectionBiasedAddComplexFog = 9,
        MultipurposeMaskDetailBeforeReflectionBiasedMultiply = 10,
        MultipurposeMaskDetailBeforeReflectionBiasedMultiplyComplexFog = 11,
        MultipurposeMaskDetailBeforeReflectionMultiply = 12,
        MultipurposeMaskDetailBeforeReflectionMultiplyComplexFog = 13,
        MultipurposeMaskInverseDetailAfterReflectionBiasedAdd = 14,
        MultipurposeMaskInverseDetailAfterReflectionBiasedAddComplexFog = 15,
        MultipurposeMaskInverseDetailAfterReflectionBiasedMultiply = 16,
        MultipurposeMaskInverseDetailAfterReflectionBiasedMultiplyComplexFog = 17,
        MultipurposeMaskInverseDetailAfterReflectionMultiply = 18,
        MultipurposeMaskInverseDetailAfterReflectionMultiplyComplexFog = 19,
        MultipurposeMaskInverseDetailBeforeReflectionBiasedAdd = 20,
        MultipurposeMaskInverseDetailBeforeReflectionBiasedAddComplexFog = 21,
        MultipurposeMaskInverseDetailBeforeReflectionBiasedMultiply = 22,
        MultipurposeMaskInverseDetailBeforeReflectionBiasedMultiplyComplexFog = 23,
        MultipurposeMaskInverseDetailBeforeReflectionMultiply = 24,
        MultipurposeMaskInverseDetailBeforeReflectionMultiplyComplexFog = 1
    },
    model_mask_none = {
        NoMaskDetailAfterReflectionBiasedAdd = 2,
        NoMaskDetailAfterReflectionBiasedAddComplexFog = 3,
        NoMaskDetailAfterReflectionBiasedAddSelfIllumination = 18,
        NoMaskDetailAfterReflectionBiasedMultiply = 4,
        NoMaskDetailAfterReflectionBiasedMultiplyComplexFog = 5,
        NoMaskDetailAfterReflectionBiasedMultiplySelfIllumination = 16,
        NoMaskDetailAfterReflectionMultiply = 6,
        NoMaskDetailAfterReflectionMultiplyComplexFog = 7,
        NoMaskDetailAfterReflectionMultiplySelfIllumination = 17,
        NoMaskDetailBeforeReflectionBiasedAdd = 8,
        NoMaskDetailBeforeReflectionBiasedAddComplexFog = 9,
        NoMaskDetailBeforeReflectionBiasedAddSelfIllumination = 15,
        NoMaskDetailBeforeReflectionBiasedMultiply = 10,
        NoMaskDetailBeforeReflectionBiasedMultiplyComplexFog = 11,
        NoMaskDetailBeforeReflectionBiasedMultiplySelfIllumination = 13,
        NoMaskDetailBeforeReflectionMultiply = 12,
        NoMaskDetailBeforeReflectionMultiplyComplexFog = 1,
        NoMaskDetailBeforeReflectionMultiplySelfIllumination = 14
    },
    model_mask_reflection = {
        ReflectionMaskDetailAfterReflectionBiasedAdd = 2,
        ReflectionMaskDetailAfterReflectionBiasedAddComplexFog = 3,
        ReflectionMaskDetailAfterReflectionBiasedMultiply = 4,
        ReflectionMaskDetailAfterReflectionBiasedMultiplyComplexFog = 5,
        ReflectionMaskDetailAfterReflectionMultiply = 6,
        ReflectionMaskDetailAfterReflectionMultiplyComplexFog = 7,
        ReflectionMaskDetailBeforeReflectionBiasedAdd = 8,
        ReflectionMaskDetailBeforeReflectionBiasedAddComplexFog = 9,
        ReflectionMaskDetailBeforeReflectionBiasedMultiply = 10,
        ReflectionMaskDetailBeforeReflectionBiasedMultiplyComplexFog = 11,
        ReflectionMaskDetailBeforeReflectionMultiply = 12,
        ReflectionMaskDetailBeforeReflectionMultiplyComplexFog = 13,
        ReflectionMaskInverseDetailAfterReflectionBiasedAdd = 14,
        ReflectionMaskInverseDetailAfterReflectionBiasedAddComplexFog = 15,
        ReflectionMaskInverseDetailAfterReflectionBiasedMultiply = 16,
        ReflectionMaskInverseDetailAfterReflectionBiasedMultiplyComplexFog = 17,
        ReflectionMaskInverseDetailAfterReflectionMultiply = 18,
        ReflectionMaskInverseDetailAfterReflectionMultiplyComplexFog = 19,
        ReflectionMaskInverseDetailBeforeReflectionBiasedAdd = 20,
        ReflectionMaskInverseDetailBeforeReflectionBiasedAddComplexFog = 21,
        ReflectionMaskInverseDetailBeforeReflectionBiasedMultiply = 22,
        ReflectionMaskInverseDetailBeforeReflectionBiasedMultiplyComplexFog = 23,
        ReflectionMaskInverseDetailBeforeReflectionMultiply = 24,
        ReflectionMaskInverseDetailBeforeReflectionMultiplyComplexFog = 1
    },
    model_mask_self_illumination = {
        SelfIlluminationMaskDetailAfterReflectionBiasedAdd = 2,
        SelfIlluminationMaskDetailAfterReflectionBiasedAddComplexFog = 3,
        SelfIlluminationMaskDetailAfterReflectionBiasedMultiply = 4,
        SelfIlluminationMaskDetailAfterReflectionBiasedMultiplyComplexFog = 5,
        SelfIlluminationMaskDetailAfterReflectionMultiply = 6,
        SelfIlluminationMaskDetailAfterReflectionMultiplyComplexFog = 7,
        SelfIlluminationMaskDetailBeforeReflectionBiasedAdd = 8,
        SelfIlluminationMaskDetailBeforeReflectionBiasedAddComplexFog = 9,
        SelfIlluminationMaskDetailBeforeReflectionBiasedMultiply = 10,
        SelfIlluminationMaskDetailBeforeReflectionBiasedMultiplyComplexFog = 11,
        SelfIlluminationMaskDetailBeforeReflectionMultiply = 12,
        SelfIlluminationMaskDetailBeforeReflectionMultiplyComplexFog = 13,
        SelfIlluminationMaskInverseDetailAfterReflectionBiasedAdd = 14,
        SelfIlluminationMaskInverseDetailAfterReflectionBiasedAddComplexFog = 15,
        SelfIlluminationMaskInverseDetailAfterReflectionBiasedMultiply = 16,
        SelfIlluminationMaskInverseDetailAfterReflectionBiasedMultiplyComplexFog = 17,
        SelfIlluminationMaskInverseDetailAfterReflectionMultiply = 18,
        SelfIlluminationMaskInverseDetailAfterReflectionMultiplyComplexFog = 19,
        SelfIlluminationMaskInverseDetailBeforeReflectionBiasedAdd = 20,
        SelfIlluminationMaskInverseDetailBeforeReflectionBiasedAddComplexFog = 21,
        SelfIlluminationMaskInverseDetailBeforeReflectionBiasedMultiply = 22,
        SelfIlluminationMaskInverseDetailBeforeReflectionBiasedMultiplyComplexFog = 23,
        SelfIlluminationMaskInverseDetailBeforeReflectionMultiply = 24,
        SelfIlluminationMaskInverseDetailBeforeReflectionMultiplyComplexFog = 1
    },
    screen_effect = {
        VideoOffConvolved = 14,
        VideoOffConvolvedFilterDesaturation = 6,
        VideoOffConvolvedFilterLight = 5,
        VideoOffConvolvedFilterLightAndDesaturation = 4,
        VideoOffConvolvedMask = 13,
        VideoOffConvolvedMaskFilterDesaturation = 3,
        VideoOffConvolvedMaskFilterLight = 2,
        VideoOffConvolvedMaskFilterLightAndDesaturation = 1,
        VideoOffConvolvedMaskThreeStage = 12,
        VideoOffNonConvolved = 7,
        VideoOffNonConvolvedMask = 9,
        VideoOffNonConvolvedPassThrough = 8,
        VideoOnPass0 = 10,
        VideoOnPass1 = 11
    },
    screen_effect_non_video = {ScreenEffectNonVideoPass0 = 1, ScreenEffectNonVideoPass1 = 2},
    screen_effect_non_video_convolution_mask = {ScreenEffectNonVideoConvolutionMask = 1},
    screen_effect_non_video_convolution_none = {
        PassThrough_1 = 1,
        PassThrough_2 = 2,
        PassThrough_non_convolved = 3
    },
    screen_effect_non_video_no_convolution_mask = {ScreenEffectNonVideoNoConvolutionMask = 1},
    screen_effect_video = {ScreenEffectVideo = 1},
    screen_flash = {FlashInvert = 1},
    screen_meter = {ScreenMeter = 1},
    screen_multitexture_add_add = {ScreenMultitextureAdd = 1},
    screen_multitexture_add_dot = {ScreenMultitextureAddDot = 1},
    screen_multitexture_add_multiply = {ScreenMultitextureAddMultiply = 1},
    screen_multitexture_add_multiply2x = {ScreenMultitextureAddMultiply2x = 1},
    screen_multitexture_add_subtract = {ScreenMultitextureAddSubtract = 1},
    screen_multitexture_dot_add = {ScreenMultitextureDotAdd = 1},
    screen_multitexture_dot_dot = {ScreenMultitextureDotDot = 1},
    screen_multitexture_dot_multiply = {ScreenMultitextureDotMulitply = 1},
    screen_multitexture_dot_multiply2x = {ScreenMultitextureDotMulitply2x = 1},
    screen_multitexture_dot_subtract = {ScreenMultitextureDotSubtract = 1},
    screen_multitexture_multiply2x_add = {ScreenMultitextureMultiply2xAdd = 1},
    screen_multitexture_multiply2x_dot = {ScreenMultitextureMultiply2xDot = 1},
    screen_multitexture_multiply2x_multiply = {ScreenMultitextureMultiply2xMultiply = 1},
    screen_multitexture_multiply2x_multiply2x = {ScreenMultitextureMultiply2xMultiply2x = 1},
    screen_multitexture_multiply2x_subtract = {ScreenMultitextureMultiply2xSubtract = 1},
    screen_multitexture_multiply_add = {ScreenMultitextureMultiplyAdd = 1},
    screen_multitexture_multiply_dot = {ScreenMultitextureMultiplyDot = 1},
    screen_multitexture_multiply_multiply = {ScreenMultitextureMultiplyMultiply = 1},
    screen_multitexture_multiply_multiply2x = {ScreenMultitextureMultiplyMultiply2x = 1},
    screen_multitexture_multiply_subtract = {ScreenMultitextureMultiplySubtract = 1},
    screen_multitexture_subtract_add = {ScreenMultitextureSubtractAdd = 1},
    screen_multitexture_subtract_dot = {ScreenMultitextureSubtractDot = 1},
    screen_multitexture_subtract_multiply = {ScreenMultitextureSubtractMultiply = 1},
    screen_multitexture_subtract_multiply2x = {ScreenMultitextureSubtractMultiply2x = 1},
    screen_multitexture_subtract_subtract = {ScreenMultitextureSubtractSubtract = 1},
    screen_normal = {ScreenNormal = 1},
    shadow_convolve = {ShadowConvolve = 1},
    sun_glow_convolve = {SunGlowConvolve = 2, SunGlowCopySource = 1},
    sun_glow_draw = {SunGlowDraw = 1},
    transparent_generic = {TransparentGeneric = 1},
    transparent_glass_diffuse = {
        TransparentGlassDiffuseEnvironment = 2,
        TransparentGlassDiffuseModel = 1
    },
    transparent_glass_reflection_bumped = {TransparentGlassReflectionBumped = 1},
    transparent_glass_reflection_flat = {
        GlassReflectionFlat = 1,
        GlassReflectionFlatSpecularMask = 2
    },
    transparent_glass_reflection_mirror = {
        GlassReflectionMirror = 1,
        GlassReflectionMirrorSpecularMask = 2
    },
    transparent_glass_tint = {TransparentGlassTint = 1},
    transparent_meter = {TransparentMeter = 1},
    transparent_plasma = {TransparentPlasma = 1},
    transparent_water_bumpmap_convolution = {TransparentWaterBumpmapConvolution = 1},
    transparent_water_opacity = {
        TransparentWaterOpacityAlphaModulated = 1,
        TransparentWaterOpacityColorModulated = 2
    },
    transparent_water_reflection = {TransparentWaterReflection = 1},
    widget_sprite = {
        WidgetSprite = 1, -- Looks like a typo was made, lets fix that
        WidgetSpritet = 1
    }
}

local pixelShaderFunctionMapping = {
    transparent_water_opacity = {
        {"main_T0_P0", "TransparentWaterOpacityAlphaModulated"},
        {"main_T0_P1", "TransparentWaterOpacityColorModulated"}
    },
    active_camouflage_draw = {{"main_T0_P0", "TintEdgeDensity"}, {"main_T0_P1", "NoEdgeTint"}},
    model_environment = {
        {"main_T0_P0", "EnvironmentNoMaskDetailBeforeReflectionBiasedMultiply"},
        {"main_T1_P0", "EnvironmentNoMaskDetailBeforeReflectionMultiply"},
        {"main_T2_P0", "EnvironmentNoMaskDetailBeforeReflectionBiasedAdd"},
        {"main_T3_P0", "EnvironmentNoMaskDetailAfterReflectionBiasedMultiply"},
        {"main_T4_P0", "EnvironmentNoMaskDetailAfterReflectionMultiply"},
        {"main_T5_P0", "EnvironmentNoMaskDetailAfterReflectionBiasedAdd"},
        {"main_T6_P0", "EnvironmentNoMaskDetailBeforeReflectionBiasedMultiplyComplexFog"},
        {"main_T7_P0", "EnvironmentNoMaskDetailBeforeReflectionMultiplyComplexFog"},
        {"main_T8_P0", "EnvironmentNoMaskDetailBeforeReflectionBiasedAddComplexFog"},
        {"main_T9_P0", "EnvironmentNoMaskDetailAfterReflectionBiasedMultiplyComplexFog"},
        {"main_T10_P0", "EnvironmentNoMaskDetailAfterReflectionMultiplyComplexFog"},
        {"main_T11_P0", "EnvironmentNoMaskDetailAfterReflectionBiasedAddComplexFog"}
    },
    model_mask_multipurpose = {
        {"main_T0_P0", "MultipurposeMaskInverseDetailBeforeReflectionBiasedMultiply"},
        {"main_T1_P0", "MultipurposeMaskInverseDetailBeforeReflectionMultiply"},
        {"main_T2_P0", "MultipurposeMaskInverseDetailBeforeReflectionBiasedAdd"},
        {"main_T3_P0", "MultipurposeMaskInverseDetailAfterReflectionBiasedMultiply"},
        {"main_T4_P0", "MultipurposeMaskInverseDetailAfterReflectionMultiply"},
        {"main_T5_P0", "MultipurposeMaskInverseDetailAfterReflectionBiasedAdd"},
        {"main_T6_P0", "MultipurposeMaskDetailBeforeReflectionBiasedMultiply"},
        {"main_T7_P0", "MultipurposeMaskDetailBeforeReflectionMultiply"},
        {"main_T8_P0", "MultipurposeMaskDetailBeforeReflectionBiasedAdd"},
        {"main_T9_P0", "MultipurposeMaskDetailAfterReflectionBiasedMultiply"},
        {"main_T10_P0", "MultipurposeMaskDetailAfterReflectionMultiply"},
        {"main_T11_P0", "MultipurposeMaskDetailAfterReflectionBiasedAdd"},
        {"main_T12_P0", "MultipurposeMaskInverseDetailBeforeReflectionBiasedMultiplyComplexFog"},
        {"main_T13_P0", "MultipurposeMaskInverseDetailBeforeReflectionMultiplyComplexFog"},
        {"main_T14_P0", "MultipurposeMaskInverseDetailBeforeReflectionBiasedAddComplexFog"},
        {"main_T15_P0", "MultipurposeMaskInverseDetailAfterReflectionBiasedMultiplyComplexFog"},
        {"main_T16_P0", "MultipurposeMaskInverseDetailAfterReflectionMultiplyComplexFog"},
        {"main_T17_P0", "MultipurposeMaskInverseDetailAfterReflectionBiasedAddComplexFog"},
        {"main_T18_P0", "MultipurposeMaskDetailBeforeReflectionBiasedMultiplyComplexFog"},
        {"main_T19_P0", "MultipurposeMaskDetailBeforeReflectionMultiplyComplexFog"},
        {"main_T20_P0", "MultipurposeMaskDetailBeforeReflectionBiasedAddComplexFog"},
        {"main_T21_P0", "MultipurposeMaskDetailAfterReflectionBiasedMultiplyComplexFog"},
        {"main_T22_P0", "MultipurposeMaskDetailAfterReflectionMultiplyComplexFog"},
        {"main_T23_P0", "MultipurposeMaskDetailAfterReflectionBiasedAddComplexFog"}
    },
    model_mask_reflection = {
        {"main_T0_P0", "ReflectionMaskInverseDetailBeforeReflectionBiasedMultiply"},
        {"main_T1_P0", "ReflectionMaskInverseDetailBeforeReflectionMultiply"},
        {"main_T2_P0", "ReflectionMaskInverseDetailBeforeReflectionBiasedAdd"},
        {"main_T3_P0", "ReflectionMaskInverseDetailAfterReflectionBiasedMultiply"},
        {"main_T4_P0", "ReflectionMaskInverseDetailAfterReflectionMultiply"},
        {"main_T5_P0", "ReflectionMaskInverseDetailAfterReflectionBiasedAdd"},
        {"main_T6_P0", "ReflectionMaskDetailBeforeReflectionBiasedMultiply"},
        {"main_T7_P0", "ReflectionMaskDetailBeforeReflectionMultiply"},
        {"main_T8_P0", "ReflectionMaskDetailBeforeReflectionBiasedAdd"},
        {"main_T9_P0", "ReflectionMaskDetailAfterReflectionBiasedMultiply"},
        {"main_T10_P0", "ReflectionMaskDetailAfterReflectionMultiply"},
        {"main_T11_P0", "ReflectionMaskDetailAfterReflectionBiasedAdd"},
        {"main_T12_P0", "ReflectionMaskInverseDetailBeforeReflectionBiasedMultiplyComplexFog"},
        {"main_T13_P0", "ReflectionMaskInverseDetailBeforeReflectionMultiplyComplexFog"},
        {"main_T14_P0", "ReflectionMaskInverseDetailBeforeReflectionBiasedAddComplexFog"},
        {"main_T15_P0", "ReflectionMaskInverseDetailAfterReflectionBiasedMultiplyComplexFog"},
        {"main_T16_P0", "ReflectionMaskInverseDetailAfterReflectionMultiplyComplexFog"},
        {"main_T17_P0", "ReflectionMaskInverseDetailAfterReflectionBiasedAddComplexFog"},
        {"main_T18_P0", "ReflectionMaskDetailBeforeReflectionBiasedMultiplyComplexFog"},
        {"main_T19_P0", "ReflectionMaskDetailBeforeReflectionMultiplyComplexFog"},
        {"main_T20_P0", "ReflectionMaskDetailBeforeReflectionBiasedAddComplexFog"},
        {"main_T21_P0", "ReflectionMaskDetailAfterReflectionBiasedMultiplyComplexFog"},
        {"main_T22_P0", "ReflectionMaskDetailAfterReflectionMultiplyComplexFog"},
        {"main_T23_P0", "ReflectionMaskDetailAfterReflectionBiasedAddComplexFog"}
    },
    model_mask_change_color = {
        {"main_T0_P0", "ChangeColorMaskInverseDetailBeforeReflectionBiasedMultiply"},
        {"main_T1_P0", "ChangeColorMaskInverseDetailBeforeReflectionMultiply"},
        {"main_T2_P0", "ChangeColorMaskInverseDetailBeforeReflectionBiasedAdd"},
        {"main_T3_P0", "ChangeColorMaskInverseDetailAfterReflectionBiasedMultiply"},
        {"main_T4_P0", "ChangeColorMaskInverseDetailAfterReflectionMultiply"},
        {"main_T5_P0", "ChangeColorMaskInverseDetailAfterReflectionBiasedAdd"},
        {"main_T6_P0", "ChangeColorMaskDetailBeforeReflectionBiasedMultiply"},
        {"main_T7_P0", "ChangeColorMaskDetailBeforeReflectionMultiply"},
        {"main_T8_P0", "ChangeColorMaskDetailBeforeReflectionBiasedAdd"},
        {"main_T9_P0", "ChangeColorMaskDetailAfterReflectionBiasedMultiply"},
        {"main_T10_P0", "ChangeColorMaskDetailAfterReflectionMultiply"},
        {"main_T11_P0", "ChangeColorMaskDetailAfterReflectionBiasedAdd"},
        {"main_T12_P0", "ChangeColorMaskInverseDetailBeforeReflectionBiasedMultiplyComplexFog"},
        {"main_T13_P0", "ChangeColorMaskInverseDetailBeforeReflectionMultiplyComplexFog"},
        {"main_T14_P0", "ChangeColorMaskInverseDetailBeforeReflectionBiasedAddComplexFog"},
        {"main_T15_P0", "ChangeColorMaskInverseDetailAfterReflectionBiasedMultiplyComplexFog"},
        {"main_T16_P0", "ChangeColorMaskInverseDetailAfterReflectionMultiplyComplexFog"},
        {"main_T17_P0", "ChangeColorMaskInverseDetailAfterReflectionBiasedAddComplexFog"},
        {"main_T18_P0", "ChangeColorMaskDetailBeforeReflectionBiasedMultiplyComplexFog"},
        {"main_T19_P0", "ChangeColorMaskDetailBeforeReflectionMultiplyComplexFog"},
        {"main_T20_P0", "ChangeColorMaskDetailBeforeReflectionBiasedAddComplexFog"},
        {"main_T21_P0", "ChangeColorMaskDetailAfterReflectionBiasedMultiplyComplexFog"},
        {"main_T22_P0", "ChangeColorMaskDetailAfterReflectionMultiplyComplexFog"},
        {"main_T23_P0", "ChangeColorMaskDetailAfterReflectionBiasedAddComplexFog"}
    },
    model_mask_none = {
        {"main_T0_P0", "NoMaskDetailBeforeReflectionBiasedMultiply"},
        {"main_T1_P0", "NoMaskDetailBeforeReflectionMultiply"},
        {"main_T2_P0", "NoMaskDetailBeforeReflectionBiasedAdd"},
        {"main_T3_P0", "NoMaskDetailAfterReflectionBiasedMultiply"},
        {"main_T4_P0", "NoMaskDetailAfterReflectionMultiply"},
        {"main_T5_P0", "NoMaskDetailAfterReflectionBiasedAdd"},
        {"main_T6_P0", "NoMaskDetailBeforeReflectionBiasedMultiplyComplexFog"},
        {"main_T7_P0", "NoMaskDetailBeforeReflectionMultiplyComplexFog"},
        {"main_T8_P0", "NoMaskDetailBeforeReflectionBiasedAddComplexFog"},
        {"main_T9_P0", "NoMaskDetailAfterReflectionBiasedMultiplyComplexFog"},
        {"main_T10_P0", "NoMaskDetailAfterReflectionMultiplyComplexFog"},
        {"main_T11_P0", "NoMaskDetailAfterReflectionBiasedAddComplexFog"}
    },
    model_mask_self_illumination = {
        {"main_T0_P0", "SelfIlluminationMaskInverseDetailBeforeReflectionBiasedMultiply"},
        {"main_T1_P0", "SelfIlluminationMaskInverseDetailBeforeReflectionMultiply"},
        {"main_T2_P0", "SelfIlluminationMaskInverseDetailBeforeReflectionBiasedAdd"},
        {"main_T3_P0", "SelfIlluminationMaskInverseDetailAfterReflectionBiasedMultiply"},
        {"main_T4_P0", "SelfIlluminationMaskInverseDetailAfterReflectionMultiply"},
        {"main_T5_P0", "SelfIlluminationMaskInverseDetailAfterReflectionBiasedAdd"},
        {"main_T6_P0", "SelfIlluminationMaskDetailBeforeReflectionBiasedMultiply"},
        {"main_T7_P0", "SelfIlluminationMaskDetailBeforeReflectionMultiply"},
        {"main_T8_P0", "SelfIlluminationMaskDetailBeforeReflectionBiasedAdd"},
        {"main_T9_P0", "SelfIlluminationMaskDetailAfterReflectionBiasedMultiply"},
        {"main_T10_P0", "SelfIlluminationMaskDetailAfterReflectionMultiply"},
        {"main_T11_P0", "SelfIlluminationMaskDetailAfterReflectionBiasedAdd"},
        {"main_T12_P0", "SelfIlluminationMaskInverseDetailBeforeReflectionBiasedMultiplyComplexFog"},
        {"main_T13_P0", "SelfIlluminationMaskInverseDetailBeforeReflectionMultiplyComplexFog"},
        {"main_T14_P0", "SelfIlluminationMaskInverseDetailBeforeReflectionBiasedAddComplexFog"},
        {"main_T15_P0", "SelfIlluminationMaskInverseDetailAfterReflectionBiasedMultiplyComplexFog"},
        {"main_T16_P0", "SelfIlluminationMaskInverseDetailAfterReflectionMultiplyComplexFog"},
        {"main_T17_P0", "SelfIlluminationMaskInverseDetailAfterReflectionBiasedAddComplexFog"},
        {"main_T18_P0", "SelfIlluminationMaskDetailBeforeReflectionBiasedMultiplyComplexFog"},
        {"main_T19_P0", "SelfIlluminationMaskDetailBeforeReflectionMultiplyComplexFog"},
        {"main_T20_P0", "SelfIlluminationMaskDetailBeforeReflectionBiasedAddComplexFog"},
        {"main_T21_P0", "SelfIlluminationMaskDetailAfterReflectionBiasedMultiplyComplexFog"},
        {"main_T22_P0", "SelfIlluminationMaskDetailAfterReflectionMultiplyComplexFog"},
        {"main_T23_P0", "SelfIlluminationMaskDetailAfterReflectionBiasedAddComplexFog"}
    },
    shadow_convolve = {{"main_T0_P0", "ShadowConvolve"}},
    environment_specular_light_bumped = {{"main_T0_P0", "SpecularLightBumped"}},
    environment_specular_light_flat = {{"main_T0_P0", "EnvironmentSpecularLightFlat"}},
    transparent_glass_diffuse = {
        {"main_T0_P0", "TransparentGlassDiffuseModel"},
        {"main_T0_P1", "TransparentGlassDiffuseEnvironment"}
    },
    transparent_glass_reflection_flat = {
        {"main", "GlassReflectionFlat"}
        -- {"main_T0_P1", "GlassReflectionFlatSpecularMask"}
    },
    transparent_glass_reflection_mirror = {
        {"main", "GlassReflectionMirror"}
        -- {"main_T0_P1", "GlassReflectionMirrorSpecularMask"}
    }
}

return {
    vertexShaderNames = vertexShaderNames,
    pixelShaderNames = pixelShaderNames,
    pixelShaderFunctions = pixelShaderFunctions,
    pixelShaderFunctionMapping = pixelShaderFunctionMapping,
    binaries = binaries,
    separators = separators
}
